### ISSUE TITLE
無料版が 1.48.0.0 リリースしようとするとコケるので要確認・修正

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-blocks-pro#1521]
https://github.com/vektor-inc/vk-blocks/actions/runs/3731931148/jobs/6330716057

```
Warning: Invalid argument supplied for foreach() in /var/www/html/wp-content/plugins/vk-blocks/inc/vk-blocks/utils/array-merge.php on line 26

Fatal error: Uncaught Error: Call to undefined function vk_blocks_get_custom_format_lists_inline_css() in /var/www/html/wp-content/plugins/vk-blocks/inc/vk-blocks/vk-blocks-functions.php:151
Stack trace:
#0 /var/www/html/wp-includes/class-wp-hook.php(308): vk_blocks_blocks_assets('')
#1 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#2 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /var/www/html/wp-settings.php(617): do_action('init')
#4 /wordpress-phpunit/includes/bootstrap.php(305): require_once('/var/www/html/w...')
#5 /var/www/html/wp-content/plugins/vk-blocks/test/phpunit/bootstrap.php(79): require('/wordpress-phpu...')
#6 phar:///usr/local/bin/phpunit/phpunit/Util/FileLoader.php(57): include_once('/var/www/html/w...')
#7 phar:///usr/local/bin/phpunit/phpunit/Util/FileLoader.php(45): PHPUnit\Util\FileLoader::load('/var/www/html/w...')
#8 phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php(1058): PHPUnit\Util\FileLoader::checkAndLoad('/var/www/html/w in /var/www/html/wp-content/plugins/vk-blocks/inc/vk-blocks/vk-blocks-functions.php on line 151
255
```

**Comment by kurudrive** [comment]
マージされたのでcloseします。
@shimotmk 対応ありがとうございました！
